SELECT $PARTITION.OPERACIONES_mensual(OPE_FECHA_MOVIMIENTO)  AS PARTITIONID,
       COUNT(*)                                   AS ROW_COUNT
FROM     DBO.TMP_COM_OPERACIONES_CONTABLES_NW
GROUP BY $PARTITION.OPERACIONES_mensual(OPE_FECHA_MOVIMIENTO)
ORDER BY PARTITIONID
